### ISSUE TITLE
Failed to retrieve response from server

### ISSUE THREAD

**Issue by otnasusagus** [Midtrans/Merchant-Server-for-Midtrans-Mobile-SDK-PHP-Sample#1]
saya mengintegrasikan midtrans di mobile sdk di android, dan saya menggunakan source code PHP ini untuk merchant base url yang sudah saya deploy ke heroku ("https://appmidtrans.herokuapp.com/") di kode android saya. 
setelah saya running aplikasinya tampil kesalahan seperti pada gambar di link berikut ("https://drive.google.com/open?id=18CPUxsLTDXYD6JuBP5K_MHnuewTxSxUb"), apakah ada yg kurang di midtrans saya?

**Comment by rizdaprasetya** [comment]
@otnasusagus Salah set **Merchant Base URL** di client codenya, diset apa?
Kalo dicek di server itu, harusnya diset `https://appmidtrans.herokuapp.com/index.php` supaya bisa transaksi.

**Comment by otnasusagus** [comment]
@rizdaprasetya  terimakasih, sekarang sudah bisa dijalankan.
